version: '3'

tasks:
  generate-secrets:
    desc: Generate secure passwords and secrets for .env file
    cmds:
      - python3 scripts/generate-secrets.py {{.CLI_ARGS}}
    platforms: [linux, darwin]

  generate-secrets:windows:
    desc: Generate secure passwords and secrets for .env file (Windows)
    cmds:
      - python scripts/generate-secrets.py {{.CLI_ARGS}}
    platforms: [windows]

  init:
    desc: Initialize environment (generate secrets and start services)
    cmds:
      - task: generate-secrets
      - task: up

  up:
    desc: Start all services with docker compose
    cmds:
      - docker compose up -d

  down:
    desc: Stop all services
    cmds:
      - docker compose down

  build:
    desc: Build all services
    cmds:
      - docker compose build --progress=plain
      - docker compose up -d

  logs:
    desc: View logs from all services
    cmds:
      - docker compose logs -f

  logs-auth:
    desc: View auth service logs
    cmds:
      - docker compose logs -f auth-service

  logs-public:
    desc: View public API logs
    cmds:
      - docker compose logs -f public-api

  logs-admin:
    desc: View admin API logs
    cmds:
      - docker compose logs -f admin-api

  logs-files:
    desc: View files API logs
    cmds:
      - docker compose logs -f files-api

  logs-public-web:
    desc: View public web logs
    cmds:
      - docker compose logs -f public-web

  logs-admin-web:
    desc: View admin web logs
    cmds:
      - docker compose logs -f admin-web

  logs-db:
    desc: View database logs
    cmds:
      - docker compose logs -f postgres

  restart:
    desc: Restart all services
    cmds:
      - docker compose restart

  ps:
    desc: List running services
    cmds:
      - docker compose ps

  clean:
    desc: Stop services and remove volumes
    cmds:
      - docker compose down -v

  # Stop individual services
  stop-auth:
    desc: Stop auth service
    cmds:
      - docker compose stop auth-service

  stop-public-api:
    desc: Stop public API
    cmds:
      - docker compose stop public-api

  stop-admin-api:
    desc: Stop admin API
    cmds:
      - docker compose stop admin-api

  stop-files-api:
    desc: Stop files API
    cmds:
      - docker compose stop files-api

  stop-public-web:
    desc: Stop public web
    cmds:
      - docker compose stop public-web

  stop-admin-web:
    desc: Stop admin web
    cmds:
      - docker compose stop admin-web

  # Rebuild and restart individual services
  rebuild-auth:
    desc: Rebuild and restart auth service
    cmds:
      - docker compose up -d --build auth-service

  rebuild-public-api:
    desc: Rebuild and restart public API
    cmds:
      - docker compose up -d --build public-api

  rebuild-admin-api:
    desc: Rebuild and restart admin API
    cmds:
      - docker compose up -d --build admin-api

  rebuild-files-api:
    desc: Rebuild and restart files API
    cmds:
      - docker compose up -d --build files-api

  rebuild-public-web:
    desc: Rebuild and restart public web
    cmds:
      - docker compose up -d --build public-web

  rebuild-admin-web:
    desc: Rebuild and restart admin web
    cmds:
      - docker compose up -d --build admin-web

  # CI/CD Tasks
  validate:
    desc: Validate docker compose configuration syntax
    cmds:
      - docker compose config --quiet --no-interpolate

  lint-yaml:
    desc: Lint YAML files
    cmds:
      - cmd: python -m yamllint .
        platforms: [windows]
      - cmd: yamllint .
        platforms: [linux, darwin]

  lint-shell:
    desc: Lint shell scripts
    cmds:
      - shellcheck scripts/*.sh

  lint-python:
    desc: Lint Python scripts
    cmds:
      - cmd: python -m flake8 scripts/ --max-line-length=120
        platforms: [windows]
      - cmd: flake8 scripts/ --max-line-length=120
        platforms: [linux, darwin]

  lint-markdown:
    desc: Lint Markdown files
    cmds:
      - markdownlint-cli2 "**/*.md"

  install-tools:
    desc: Install CI/CD tools (requires pip and npm)
    cmds:
      - cmd: pip install yamllint flake8
        platforms: [linux, darwin]
      - cmd: python -m pip install yamllint flake8
        platforms: [windows]
      - npm install -g markdownlint-cli2
      - cmd: echo "Note - shellcheck must be installed separately (apt, brew, etc.)"
        platforms: [linux, darwin]
      - cmd: echo Note - shellcheck must be installed separately
        platforms: [windows]

  ci:
    desc: Run all CI checks locally
    cmds:
      - task: validate
      - task: lint-yaml
      - task: lint-shell
      - task: lint-python
      - echo "✓ All CI checks passed!"
